<?php
register_post_type('media', [
  'labels' => [
    'name' => __('Medias', 'prifinance'),
    'singular_name' => __('Media', 'prifinance'),
    'add_new' => __('Add Media', 'prifinance'),
    'add_new_item' => __('Add new Media', 'prifinance'),
    'edit_item' => __('Edit Media', 'prifinance'),
    'new_item' => __('New Media', 'prifinance'),
    'view_item' => __('View Media', 'prifinance'),
    'search_items' => __('Find Media', 'prifinance'),
    'not_found' => __('Media not found', 'prifinance'),
    'not_found_in_trash' => __('Media not found', 'prifinance'),
    'parent_item_colon' => '',
    'menu_name' => __('Medias', 'prifinance'),
  ],
  'menu_icon' => 'dashicons-excerpt-view',
  'public' => false,
  'publicly_queryable' => false,
  'show_ui' => true,
  'show_in_menu' => true,
  'query_var' => false,
  'rewrite' => true,
  'capability_type' => 'post',
  'has_archive' => false,
  'hierarchical' => false,
  'menu_position' => null,
  'supports' => ['title'],
]);
